run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - revive
    - stylecheck
    - lll
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - forcetypeassert
    - gofmt
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - tenv
    - unparam
    - wastedassign

linters-settings:
  stylecheck:
    checks: [
      "*",
      "-ST1000" # disables package comment
    ]
  lll:
    line-length: 80
  revive:
    severity: warning
    confidence: 0.8

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
