run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    # - structcheck
    - typecheck
    - unused
    - varcheck
    - goimports
    - golint
    - stylecheck
    # - testpackage
    # - wrapcheck
    # - varnamelen

linters-settings:
  stylecheck:
    checks: ["*", "-ST1000"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
