run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - goimports
    - golint # replace with revive
    - stylecheck
    # - testpackage
    - lll

linters-settings:
  stylecheck:
    checks: [
      "*",
      "-ST1000" # disables package comment
    ]
  lll:
    line-length: 100 # should probably be 80

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
