# auth configs
jwt_sign_key: 'secret'
jwt_duration: '24h'

# server configs
server_address: '0.0.0.0:3000'

# postgres configs
pg_host: '0.0.0.0'
pg_port: '5432'
pg_user: 'postgres'
pg_password: '12345'
pg_dbname: 'todo'
pg_sslmode: 'disable'
